---
title: "Ovis Biocircos"
author: "D. Stuehler"
date: "2024-10-31"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
require(knitr)
opts_chunk$set(message=FALSE, warning=FALSE, comment = "", cache = F)
options(width = 200)
```

```{js}
function addSvgSaveButtonJquery(buttonId, topSvg) {
  $(buttonId).append("<a id=imgDownload></a>");
  $(buttonId).click(function() {
    var html = $($(topSvg).attr("version", 1.1)
             .attr("xmlns","http://www.w3.org/2000/svg")).clone()
      .wrap('<p/>').parent().html();
    var imgsrc = 'data:image/svg+xml;base64,' + btoa(html);
    $(buttonId + " #imgDownload").attr("download", "BioCircos_plot.svg");
    $(buttonId + " #imgDownload").attr("href", imgsrc);
    var a = $(buttonId + " #imgDownload")[0];
    a.click();
  });
}
```

```{r, fig.width=10, fig.height=10}
library(BioCircos)
library(RColorBrewer)

# Load your data from the file
snippy <- read.table("C://Bioinformatics/Heck_USDA_Pathology/Dcitri_mtDNA_haplotyping/Examining_the_effect_of_kmer_size/ska2/Rplots/Plots_for_Genome_Biology_submission/Ovis-k13-m0p1-mapped-JN181255.1-snippy-tab-for-R-input-snp-proportions.txt", 
                     sep = "\t", stringsAsFactors = F, na.strings = "NA")

colnames(snippy) <- c("Strain_ID", "Genus", "Chrom", "Pos", "Type", "Ref", "Alt", "Evidence", "FType", "Strand", "NT_pos", "AA_pos", "Effect", "Locus_tag", "Gene", "Product")

snippy[is.na(snippy)] <- ''

sniptest <- snippy
newprotsamps <- c("KY426014","KY426015","MF181946","MF181947","metasample","MF614804","MF614805","MF614806","MF614807","MF614808","MF614809","MF614810","MF614811","MF614812","MF614813","MF614814","MF614815","MF614816","MF614817","MF614818","MF614819","MF614820","MF614821","MF614822","MF614823","MF614824","MF614825","MF614826","MF614827","MF614828", "OM181946", "MF181947")
sniptest$protocol <- ifelse(sniptest$Strain_ID %in% newprotsamps, 'new_protocol', 'existing_protocol')

# use a high coverage CLas strain KY426014 as the example to plot

sniplen <- length(sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Pos)

# create a new column in sniptest to hold the read depth reported in the "Evidence"
# column by snippy
Evidence_depth <- c()
for(i in sniptest$Evidence){
  Evidence_depth <- c(Evidence_depth, as.numeric(strsplit(strsplit(strsplit(strsplit(i, " ")[[1]], " ")[[1]],":")[[1]], " ")[[2]]))
  print(as.numeric(strsplit(strsplit(strsplit(strsplit(i, " ")[[1]], " ")[[1]],":")[[1]], " ")[[2]]))
}

sniptest$SNP_depth <- Evidence_depth
# create a variable to change shape of SNP value if SNP inside a coding sequence
# or intergenic region
#sniptest$shape <- ifelse(sniptest$FType == "CDS", 'circle', 'rect')

# BioCircos plots

# genome track
Ovis <- list('JN181255.1' = 16463)

Ovis_mtDNA_CDS_arc_labels_weitz = c('ND1','ND2','COX1','COX2','ATP8','ATP6','COX3','ND3','ND4L','ND4','ND5','ND6','CYTB')
Ovis_mtDNA_CDS_arc_labels = c('ND1','ND2','COX1','COX2','ATP8','ATP6','COX3','ND3','ND4L','ND4','ND5','ND6','CYTB')
Ovis_mtDNA_CDS_arc_chroms = c('JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1')
Ovis_mtDNA_CDS_arc_start <- c(2743,3908,5330,7017,7773,7934,8614,9467,9883,10173,11751,13555,14156)
Ovis_mtDNA_CDS_arc_stop <- c(3698,4949,6874,7700,7973,8614,9397,9812,10179,11550,13571,14082,15295)

Ovis_mtDNA_tRNA_arc_labels_weitz = c('tRNA-Phe','tRNA-Val','tRNA-Leu','tRNA-Ile','tRNA-Gln','tRNA-Met','tRNA-Trp','tRNA-Ala','tRNA-Asn','tRNA-Cys','tRNA-Tyr','tRNA-Ser','tRNA-Asp','tRNA-Lys','tRNA-Gly','tRNA-Arg','tRNA-His','tRNA-Ser','tRNA-Leu','tRNA-Glu','tRNA-Thr','tRNA-Pro')
Ovis_mtDNA_tRNA_arc_labels = c('tRNA-Phe','tRNA-Val','tRNA-Leu','tRNA-Ile','tRNA-Gln','tRNA-Met','tRNA-Trp','tRNA-Ala','tRNA-Asn','tRNA-Cys','tRNA-Tyr','tRNA-Ser','tRNA-Asp','tRNA-Lys','tRNA-Gly','tRNA-Arg','tRNA-His','tRNA-Ser','tRNA-Leu','tRNA-Glu','tRNA-Thr','tRNA-Pro')
Ovis_mtDNA_tRNA_arc_chroms = c('JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1')
Ovis_mtDNA_tRNA_arc_start <- c(1,1026,2666,3699,3765,3839,4950,5018,5088,5193,5261,6872,6948,7704,9398,9814,11551,11620,11681,14083,15299,15368)
Ovis_mtDNA_tRNA_arc_stop <- c(68,1092,2740,3767,3836,3907,5016,5086,5160,5260,5328,6942,7015,7771,9466,9882,11619,11679,11750,14151,15368,15433)

Ovis_mtDNA_rRNA_arc_labels_weitz = c('12S_rRNA', '16S_rRNA')
Ovis_mtDNA_rRNA_arc_labels = c('12S_rRNA', '16S_rRNA')
Ovis_mtDNA_rRNA_arc_chroms = c('JN181255.1', 'JN181255.1')
Ovis_mtDNA_rRNA_arc_start <- c(69, 1093)
Ovis_mtDNA_rRNA_arc_stop <- c(1025, 2265)

Ovis_mtDNA_intergenic_arc_labels_weitz = c('int1', 'int2', 'int3', 'int4', 'int5', 'int6', 'int7', 'int8', 'int9', 'int10', 'int11', 'int12', 'int13', 'int14', 'int15', 'int16')
Ovis_mtDNA_intergenic_arc_labels = c('int1', 'int2', 'int3', 'int4', 'int5', 'int6', 'int7', 'int8', 'int9', 'int10', 'int11', 'int12', 'int13', 'int14', 'int15', 'int16')
Ovis_mtDNA_intergenic_arc_chroms = c('JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1', 'JN181255.1')
Ovis_mtDNA_intergenic_arc_start <- c(2266, 2741, 3837, 5017, 5087, 5161, 5329, 6943, 7016, 7701, 7772, 9813, 11680, 14152, 15296, 15434)
Ovis_mtDNA_intergenic_arc_stop <- c(2665, 2742, 3838, 5017, 5087, 5192, 5329, 6947, 7016, 7703, 7772, 9813, 11680, 14155, 15298, 16463)


CDStrack = BioCircosArcTrack('Ovis_CDS', Ovis_mtDNA_CDS_arc_chroms, Ovis_mtDNA_CDS_arc_start, Ovis_mtDNA_CDS_arc_stop,
                             minRadius = 0.45, maxRadius = 1, opacities = 0.25, labels = Ovis_mtDNA_CDS_arc_labels, colors = c("#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#6DCBBA","#35B5A5","#35B5A5"))
tRNAtrack = BioCircosArcTrack('Ovis_tRNA', Ovis_mtDNA_tRNA_arc_chroms, Ovis_mtDNA_tRNA_arc_start, Ovis_mtDNA_tRNA_arc_stop,
                              minRadius = 0.45, maxRadius = 1, opacities = 0.8, labels = Ovis_mtDNA_tRNA_arc_labels, colors = "#FFFF92")
rRNAtrack = BioCircosArcTrack('Ovis_rRNA', Ovis_mtDNA_rRNA_arc_chroms, Ovis_mtDNA_rRNA_arc_start, Ovis_mtDNA_rRNA_arc_stop,
                              minRadius = 0.45, maxRadius = 1, opacities = 0.8, labels = Ovis_mtDNA_rRNA_arc_labels, colors = "#FD6C5C")
Intergenic_track = BioCircosArcTrack('Ovis_int', Ovis_mtDNA_intergenic_arc_chroms, Ovis_mtDNA_intergenic_arc_start, Ovis_mtDNA_intergenic_arc_stop,
                                     minRadius = 0.45, maxRadius = 1, opacities = 0.8, labels = Ovis_mtDNA_intergenic_arc_labels, colors = "#B3ACDC")

#tracklist = CDStrack

# create a link track to indicate gene names of SNPs
link1 <- rep('JN181255.1', sniplen)
link2 <- rep('JN181255.1', sniplen)
linkpos1 <- sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Pos
linkpos2 <- sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Pos + 1
linklabs <- sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Gene

trackback = BioCircosBackgroundTrack("myBackgroundTrack", minRadius = 0, maxRadius = 0.46,
                                     borderSize = 0, fillColors = "#EEFFEE") 


trackback2 = BioCircosBackgroundTrack("mySNPBackgroundTrack", minRadius = 0.45, maxRadius = 1,
                                      borderSize = 0.1, borderColors = "black", fillColors = "snow") 

snpColors <- brewer.pal(length(levels(as.factor(sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Type))),"Dark2")
names(snpColors) <- levels(as.factor(sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Type))
snpColors2 <- snpColors[sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Type]

tracklist = BioCircosLinkTrack('snps', link1, link2,
                               linkpos1, link2, linkpos1, linkpos2,
                               maxRadius = 0.3, #labels = linklabs,
                               axisColor = 'white', labelColor = as.vector(snpColors2))

snplist = trackback2 + BioCircosSNPTrack('snptrack', link1, linkpos1, 
                                         sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$SNP_depth, 
                                         colors = "gray20", 
                                         labels = sniptest[which(sniptest$Genus == "Ovis" & sniptest$Strain_ID == "metasample"),]$Product, 
                                         minradius = 0.46, 
                                         maxRadius = 0.99, 
                                         shape = 'circle',
                                         size = 2)

tracklist <- tracklist + snplist
tracklist <- tracklist + BioCircosTextTrack('Genus', '\'Ovis spp.\'',
                                            x = -0.45, y = -1.32, color = 'black', weight = 'bold')

tracklist <- tracklist + CDStrack + tRNAtrack + rRNAtrack + Intergenic_track
# Create BioCircos plot
BioCircos(
  genome = Ovis, genomeFillColor = c("grey95", "grey95"), genomeTicksScale = 1e3, 
  displayGenomeBorder = TRUE, genomeBorderColor = 'black', zoom = TRUE, genomeBorderSize = 0.2,
  genomeLabelDx = 3.1, genomeLabelDy = 25, genomeLabelOrientation = -1,
  genomeTicksLen = 3.5, genomeTicksTextSize = "1.4em", tracklist = tracklist,
  elementId = "myBioCircosPlot"
)
```

```{=html}
<script>
document.addEventListener("DOMContentLoaded", function() {
  $("#myBioCircosPlot").append("<button id='save_svg'>Save As SVG</button>");
  addSvgSaveButtonJquery("#save_svg", "#myBioCircosPlot svg");
});
</script>
```